services:
  app:
    depends_on:
      - db
      - mail
    build:
      context: .
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - ./:/var/www/html/.modman/multisafepay
      - ./cscart:/var/www/html/
    environment:
      PHP_IDE_CONFIG: "serverName=app"
  db:
    image: "mysql:5.7"
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  mail:
    image: "mailhog/mailhog"
    platform: linux/x86_64
    ports:
      - "8025:8025"
  adminer:
    image: adminer:latest
    platform: linux/arm64/v8
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
  expose:
    depends_on:
      - app
    build: https://github.com/beyondcode/expose.git
    entrypoint: ["/bin/sh", "-c" , "/src/expose token ${EXPOSE_TOKEN} && sed -i -E \"s/'dns'\\s?=>\\s?'.*'/'dns' => true/g\" /root/.expose/config.php  && /src/expose share app --server-host=${EXPOSE_HOST} --subdomain=${APP_SUBDOMAIN}"]
    ports:
      - "4040:4040"
