on:
  push:
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Upload Release Asset
jobs:
  build:
    name: Upload Release Asset # Name of the job
    runs-on: ubuntu-latest # or windows-latest, macOS-latest
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV # Extract the version number from the tag
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the code
      - name: Install hub
        run: sudo apt-get update && sudo apt-get install -y hub
      - name: Build project
        run: ./bin/release.sh ${{ steps.get_version.outputs.VERSION }} # Build the project
      - name: Upload Release Asset
        run: |
          set -x
          assets=()
          for asset in ./.dist/*.zip; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "Release $tag_name" "$tag_name" -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
